name: Daily Doc Scrape
on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - name: Install dependencies
        run: npm install
        
      - name: Run scraper
        run: node scraper.js
        
      - name: Save results
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs-data
          folder: .
          target-folder: scraped-data